# Generated by Django 3.2.9 on 2021-11-22 05:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='areaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAMedica', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomComuna', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDoc', models.CharField(max_length=50)),
                ('aPatDoc', models.CharField(max_length=50)),
                ('rutDoc', models.CharField(max_length=50)),
                ('emailDoc', models.CharField(max_length=50)),
                ('bornDateDoc', models.DateTimeField(blank=True, null=True)),
                ('adressDoc', models.CharField(max_length=70)),
                ('fkAMedica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areamedica')),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
            ],
        ),
        migrations.CreateModel(
            name='gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomGender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='horaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=5)),
                ('fecha', models.DateTimeField(blank=True)),
                ('fkMedico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usercontact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameContact', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('msn', models.TextField(max_length=400)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='secretaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomSec', models.CharField(max_length=50)),
                ('aPatSec', models.CharField(max_length=50)),
                ('rutSec', models.CharField(max_length=50)),
                ('emailSec', models.CharField(max_length=50)),
                ('bornDateSec', models.DateTimeField(blank=True, null=True)),
                ('adressSec', models.CharField(max_length=70)),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('fkGender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRegion', models.CharField(max_length=50)),
                ('fkPais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais')),
            ],
        ),
        migrations.CreateModel(
            name='pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorPAg', models.IntegerField()),
                ('fkAreaMedica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areamedica')),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPac', models.CharField(max_length=50)),
                ('aPatPac', models.CharField(max_length=50)),
                ('rutPac', models.CharField(max_length=50)),
                ('emailPac', models.CharField(max_length=50)),
                ('bornDatePAc', models.DateTimeField(blank=True, null=True)),
                ('adressPac', models.CharField(max_length=70)),
                ('fkComuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.comuna')),
                ('fkGender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.gender')),
            ],
        ),
        migrations.CreateModel(
            name='informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaIfo', models.DateTimeField(default=django.utils.timezone.now)),
                ('comision', models.IntegerField()),
                ('fkHoraMedica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horamedica')),
                ('fkSecretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.secretaria')),
            ],
        ),
        migrations.AddField(
            model_name='horamedica',
            name='fkPaciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paciente'),
        ),
        migrations.AddField(
            model_name='horamedica',
            name='fkPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pago'),
        ),
        migrations.AddField(
            model_name='horamedica',
            name='fkTipoPago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopago'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='fkGender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.gender'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='fkRegion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.region'),
        ),
        migrations.CreateModel(
            name='comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaComPago', models.DateTimeField(default=django.utils.timezone.now)),
                ('fkHoraMedica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.horamedica')),
            ],
        ),
    ]
